Add type_as attribute to specta
oscartbeaumont/rspc pull request #91
Opened 2022-11-28 16:22 UTC by mablin7

We were looking into using specta in our project, but ran into the issue of needing an escape hatch for certain types that can't (easily) implement `Type`.  This solution is similar to ts_rs's `#[ts(type = "..")]` attribute.

`#[specta(type_as = <Ident>)]` on a field overrides its type in the generated type definition with the type of the identifier.

Example:
```rust
use specta::{ts::ts_export, Type};

pub enum MyEnum {
    A,
    B,
    C,
}

#[derive(Type)]
pub struct MyCustomType {
    #[specta(type_as=String)]
    pub nested: MyEnum,
}

fn main() {
    println!("{}", ts_export::<MyCustomType>().unwrap(),);
}
```

Any feedback is super appreciated!

2022-11-29 00:55 UTC, Brendonovich requested changes
Thanks for working on this! Super cool idea to override the Rust type that is used rather than writing custom typescript.
I'd like the feature to mirror `ts-rs` a bit more, but you've already done quite a good job.
I might rebase this PR onto a bunch of new changes to Specta that are being made in preparation to make it more of a standalone library, I'll handle that though.

2022-11-29 00:55 UTC, Brendonovich commented on crates/specta/tests/ts_rs/field_override.rs
> +fn test() {
The `ts_rs` tests are meant to be close reflections of `ts-rs`'s actual tests - the relevant one for type overrides is [here](https://github.com/Aleph-Alpha/ts-rs/blob/f2dbbc8c10ba7071acddbe69480edfd7cfe0fbc7/ts-rs/tests/type_override.rs). Just change the file name and make the `ts-rs` test work with Specta and it's fine.

2022-11-29 00:55 UTC, Brendonovich commented on crates/specta/examples/type_as.rs
> +fn main() {
Idk if an entire example is needed but ehh I'm nitpicking

2022-11-29 00:55 UTC, Brendonovich commented on crates/specta/macros/src/type/attr/field.rs
> +    pub type_as: Option<Type>,
`ts-rs` uses the `type` option, which I think is a nicer name than `type_as`

2022-11-29 01:09 UTC, Brendonovich commented
Also would you mind explaining why you need type overrides, and why you picked Specta over `ts-rs`? Just curious haha

2022-11-30 13:15 UTC, Brendonovich approved these changes

2022-11-30 13:18 UTC, oscartbeaumont approved these changes
Thanks for your time. Looks great!

2022-11-30 13:19 UTC, merged

2022-11-30 13:29 UTC, mablin7 commented
> Also would you mind explaining why you need type overrides, and why you picked Specta over `ts-rs`? Just curious haha

Oh, sorry I didn't have the time to address your comments, thanks for the corrections.

Our main problem was that the messages in our tauri app included types from 3rd party crates that we normally just serialize to string, but we can't have them implement Type. 

The reason we would like to use specta is its ability to generate all referenced type definitions recursively. With ts-rs we have a huge list of types that need to be printed, and it needs to be updated manually. Whereas with specta, it would just be a single call, since we already have all relevant types in an enum anyway.